name: mm_core
description: "MeetMighty Core lib"
version: 1.0.0
repository: https://github.com/appmeetmighty/mm_core
issue_tracker: https://github.com/appmeetmighty/mm_coreissues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  encrypt: ^5.0.3
  crypto: ^3.0.6
  http: ^1.3.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  internet_connection_checker: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
